#ifndef _PINS_H
#define _PINS_H
#include "main.h"


#define SPEAKER_PORT	GPIOA
#define SPEAKER_PIN 	GPIO_Pin_4

#define BUTTON0_PORT 	GPIOE
#define BUTTON1_PORT 	GPIOE
#define BUTTON2_PORT 	GPIOE
#define BUTTON3_PORT	GPIOD
#define BUTTON4_PORT 	GPIOD
#define BUTTON5_PORT	GPIOD
#define BUTTON6_PORT 	GPIOD
#define BUTTON7_PORT 	GPIOE
#define BUTTON8_PORT 	GPIOE
#define BUTTON9_PORT	GPIOE
#define BUTTON10_PORT 	GPIOE
#define BUTTON11_PORT	GPIOE
#define BUTTON12_PORT 	GPIOE
#define BUTTON13_PORT 	GPIOE

static GPIO_TypeDef* BUTTON_PORT[] = {(const GPIO_TypeDef*)BUTTON0_PORT, (const GPIO_TypeDef*)BUTTON1_PORT, 
	(const GPIO_TypeDef*)BUTTON2_PORT, (const GPIO_TypeDef*)BUTTON3_PORT, (const GPIO_TypeDef*)BUTTON4_PORT, 
	(const GPIO_TypeDef*)BUTTON5_PORT, (const GPIO_TypeDef*)BUTTON6_PORT, (const GPIO_TypeDef*)BUTTON7_PORT,
	(const GPIO_TypeDef*)BUTTON8_PORT, (const GPIO_TypeDef*)BUTTON9_PORT, (const GPIO_TypeDef*)BUTTON10_PORT,
	(const GPIO_TypeDef*)BUTTON11_PORT, (const GPIO_TypeDef*)BUTTON12_PORT, (const GPIO_TypeDef*)BUTTON13_PORT};

#define BUTTON0_PIN		GPIO_Pin_6
#define BUTTON1_PIN 	GPIO_Pin_5
#define BUTTON2_PIN		GPIO_Pin_4
#define BUTTON3_PIN 	GPIO_Pin_3
#define BUTTON4_PIN 	GPIO_Pin_2
#define BUTTON5_PIN 	GPIO_Pin_1
#define BUTTON6_PIN 	GPIO_Pin_0
#define BUTTON7_PIN 	GPIO_Pin_13
#define BUTTON8_PIN 	GPIO_Pin_12
#define BUTTON9_PIN 	GPIO_Pin_11
#define BUTTON10_PIN 	GPIO_Pin_10
#define BUTTON11_PIN 	GPIO_Pin_9
#define BUTTON12_PIN 	GPIO_Pin_8
#define BUTTON13_PIN 	GPIO_Pin_7

static uint16_t BUTTON_PIN[] = {BUTTON0_PIN, BUTTON1_PIN, BUTTON2_PIN, BUTTON3_PIN, BUTTON4_PIN, BUTTON5_PIN,
	BUTTON6_PIN,BUTTON7_PIN,BUTTON8_PIN, BUTTON9_PIN,BUTTON10_PIN,BUTTON11_PIN,BUTTON12_PIN,BUTTON13_PIN};

#define CUSTOMTOGGLE_PORT0	GPIOB
#define CUSTOMTOGGLE_PORT1	GPIOB
#define CUSTOMTOGGLE_PORT2 	GPIOB
#define CUSTOMTOGGLE_PORT3 	GPIOB

#define TOGGLE_SWITCH0		GPIO_Pin_11
#define TOGGLE_SWITCH1		GPIO_Pin_12
#define TOGGLE_SWITCH2		GPIO_Pin_13
#define TOGGLE_SWITCH3		GPIO_Pin_14


#endif /* _PINS_H */