#ifndef _PINS_H
#define _PINS_H
#include "main.h"


#define SPEAKER_PORT	GPIOA
#define SPEAKER_PIN 	GPIO_Pin_4

#define BUTTON0_PORT 	GPIOD
#define BUTTON1_PORT 	GPIOD
#define BUTTON2_PORT 	GPIOD
#define BUTTON3_PORT	GPIOD
#define BUTTON4_PORT 	GPIOE
#define BUTTON5_PORT	GPIOE
#define BUTTON6_PORT 	GPIOE
#define BUTTON7_PORT 	GPIOE
#define BUTTON8_PORT 	GPIOE
#define BUTTON9_PORT	GPIOE
#define BUTTON10_PORT 	GPIOE
#define BUTTON11_PORT	GPIOE
#define BUTTON12_PORT 	GPIOE
#define BUTTON13_PORT 	GPIOE

#define BUTTON0_PIN		GPIO_Pin_0
#define BUTTON1_PIN 	GPIO_Pin_2
#define BUTTON2_PIN		GPIO_Pin_3
#define BUTTON3_PIN 	GPIO_Pin_3
#define BUTTON4_PIN 	GPIO_Pin_4
#define BUTTON5_PIN 	GPIO_Pin_5
#define BUTTON6_PIN 	GPIO_Pin_6
#define BUTTON7_PIN 	GPIO_Pin_7
#define BUTTON8_PIN 	GPIO_Pin_8
#define BUTTON9_PIN 	GPIO_Pin_9
#define BUTTON10_PIN 	GPIO_Pin_10
#define BUTTON11_PIN 	GPIO_Pin_11
#define BUTTON12_PIN 	GPIO_Pin_12
#define BUTTON13_PIN 	GPIO_Pin_13

#define TOGGLE_PORT0	GPIOB
#define TOGGLE_PORT1	GPIOB
#define TOGGLE_PORT2 	GPIOB
#define TOGGLE_PORT3 	GPIOB

#define TOGGLE_SWITCH0	GPIO_Pin_11
#define TOGGLE_SWITCH1	GPIO_Pin_12
#define TOGGLE_SWITCH2	GPIO_Pin_13
#define TOGGLE_SWITCH3	GPIO_Pin_14


#endif /* _PINS_H */
